## Numpy Temelleri

In [1]:
import numpy as np #kütüphane içe aktarıldı

In [2]:
# 1*15lik bir array olusturalım

dizi = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
dizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
# array boyutuna bakalım 

dizi.shape

(15,)

In [4]:
# 1*15'lik arrayi 3*5lik arraye dönüştürelim

dizi2 = dizi.reshape(3,5)

In [6]:
print("Şekil: ", dizi2.shape)
print("Boyut: ", dizi2.ndim)

Şekil:  (3, 5)
Boyut:  2


In [7]:
print("Veri tipi: ", dizi2.dtype.name) #array iç. bulunan verinin tipi
print("Boy: ", dizi2.size) #arrayin boyu 3*5=15 toplam boyutbilgisi

Veri tipi:  int32
Boy:  15


In [8]:
print("type:", type(dizi2))

type: <class 'numpy.ndarray'>


In [10]:
# 2 boyutlu array olusturalım

dizi2D = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,5]])
dizi2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 5]])

In [11]:
# sıfırlardan olusan array olusturalım

sifir_dizi= np.zeros((3,4))
sifir_dizi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# birlerden olusan array olusturalim

bir_dizi = np.ones((3,4))
bir_dizi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# boş bir array olusturalım

bos_dizi = np.empty((2,3))
bos_dizi

#pythonda boş 0 anlamına gelmektedir.
#aşağıda görüldüğü gibi sayılar 0a yakınsamaktadır.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# arange (x,y basamak) x'den başlar y'ye kadar (y dahil değil), basamak büyüklüğünde artarak

dizi_aralik = np.arange(10,50,5)
dizi_aralik

array([10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
# linspace(x,y basamak) x ve y arasına (x ve y dahil) basamak kadar böl

dizi_bosluk = np.linspace(10,20,5) # 10 ile 20 arasını eşit aralıklı 5 sayı ile doldur.
dizi_bosluk

array([10. , 12.5, 15. , 17.5, 20. ])

# Numpy Temel Operasyonları

* Toplama, Çıkarma, Çarpma gibi matematiksel işlemlerin nasıl yapıldığını öğreneceğiz.

* min,max,sqrt, sum ve square metotlarını öğreneceğiz.

* rastgele sayı üretecini inceleyeceğiz.

In [18]:
#matematiksel işlemler için 2 tane array olusturalım

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a)
print("")
print(b)

[1 2 3]

[4 5 6]


In [19]:
print(a+b)
print(a-b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [20]:
#filtreleme

a<2

array([ True, False, False])

In [21]:
#Hadamard çarpımı ve matris çarpımı için 2 array olusturalım.

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [22]:
#Hadamard çarpımı - norml matris çarpımından farklıdır.

print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [24]:
# Matris çarpımı

print(a)
print("")
print(b.T)
print("")

c = a.dot(b.T)
print(c)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[14 32]
 [32 77]]


In [25]:
#bir dizinin elemanlarını toplama

print(a)
a.sum()

[[1 2 3]
 [4 5 6]]


21

In [26]:
#diznin en büyük değerini bulma

a.max()

6

In [27]:
#dizinin en küçük değerini bulma

a.min()

1

In [28]:
#dizinin satırlarını toplama (axis=1)

a.sum(axis=1)

array([ 6, 15])

In [29]:
#dizinin sütunlarını toplama (axis=0)

a.sum(axis=0)

array([5, 7, 9])

In [30]:
#dizinin elemanlarının karekökünü bulma - her bir elemanın karekökünü alır ve olusturur.

np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [31]:
# dizinin elemanlarının kare kökünü bulma

np.square(a)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [34]:
# rastgele sayı üretme [0,1] arasında sürekli üniform-düzgün dağılım - 3*3 matris

rastgele_dizi = np.random.random((3,3))
rastgele_dizi

array([[0.16500185, 0.32553932, 0.2304762 ],
       [0.50739932, 0.17084146, 0.17376878],
       [0.22060325, 0.80524314, 0.41411811]])

# İndeksleme ve Dilimleme

In [35]:
dizi = np.array([1,2,3,4,5,6,7])

In [37]:
#dizinin ilk elamanı yani sıfırıncı indekste bulunan elemanı
dizi[0]

1

In [40]:
#dizinin ilk 4 elemanı

dizi[0:4] #4 dahil değil

array([1, 2, 3, 4])

In [41]:
#dizinin tersi

dizi[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [42]:
#matrislerde indeksleri ve dilimleri incelemek için 2 boyutlu bir matris oluşturalım

dizi2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
dizi2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
#dizinin 1. satır ve 1. sütunda bulunan elemanı; unutma! saymaya 0dan baslarız.

dizi2D[1,1]

7

In [44]:
#dizinin 1.sütununun tüm satırları
dizi2D[:,1]

array([2, 7])

In [45]:
#dizinin 1.satırının 1.2.3 elemanı

dizi2D[1,1:4]

array([7, 8, 9])

In [46]:
#dizinin son satırının yani 2. satırın tüm sütunları

dizi2D[-1,:] #-1 son elemana eriim sağlar

array([ 6,  7,  8,  9, 10])

In [47]:
#dizinin son sütununun tüm satırları

dizi2D[:,-1]

array([ 5, 10])

# Şekil Manipülasyonu
* Bu bölümde dizilerin şekillerinin - boyut nasıl değiştireleceğine bakacağız.

In [48]:
dizi2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
dizi2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
#vektör haline getirme 
#ravel metodu ing anlam olarak tel tel ayırma - tek boyuta düşürür.
vektor = dizi2D.ravel()
vektor

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
vektor.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
#matrislerde transpoze işlemi

dizi2D.T #satırlar sütuna, sütunlar satıra dönüşür.


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Dizileri İstifleme
* Bu bölümde dizilerin satır ve sütunlarına göre nasıl birleştirildiğini öğreneceğiz.

In [52]:
dizi1 = np.array([[1,2],[3,4]])
dizi1

array([[1, 2],
       [3, 4]])

In [53]:
dizi2 = np.array([[-1,-2],[-3,-4]])
dizi2

array([[-1, -2],
       [-3, -4]])

In [54]:
# iki diziyi alt alta ekle: sütun sayısı sabit satırları arttır.

dizi_dikey = np.vstack((dizi1,dizi2)) #-- >vertical dikey | dizi1i yukarı dizi2yi aşağı atar.
dizi_dikey

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [56]:
# iki diziyi yan yana ekle: satır sayısını sabit sütunlarını arttır.

dizi_satir = np.hstack((dizi1,dizi2)) # -- > horizontal:yatay | dizi1i sola dizi2yi sağa atar.
dizi_satir

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])